### ISSUE TITLE
Server links not working on OS X

### ISSUE THREAD

**Issue by smutch** [sunaku/dasht#12]
I installed dasht through homebrew, however, I find that the dasht-server links do nothing.  For example, the link for `numpy.add` points to `file:///Users/myusername/.local/share/dasht/docsets/NumPy.docset/Contents/Resources/Documents/doc/reference/generated/numpy.add.html#//apple_ref/Method/numpy.add`.  If I manually remove everything after and including the `#` from this then I am sent to the correct page.

**Comment by sunaku** [comment]
What browser are you using?  It works correctly for me in both w3m(1) and Firefox 46.

**Comment by smutch** [comment]
I've tried the most recent versions of both Chrome and Safari.  Both showed the same problem for me, but w3m seems to work fine...

**Comment by sunaku** [comment]
Ah then I suspect [the problem is this: Webkit browsers don't follow file links](http://sunaku.github.io/dasht/man/man1/dasht-server.1.html#browser-refuses-to-load-file-links).  It _wasn't the removal_ of the URI fragment that made the page load for you in those browsers, but rather it was the fact that you _manually submitted_ a file URL that made the difference. :neckbeard:

**Comment by smutch** [comment]
Ah.  That make sense. 😃   My apologies for not noticing that in the documentation.

Thanks for the quick follow up and the great tool!
